name: Gatsby Publish

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [contentful.deploy]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      env: 
        CONTENTFUL_ACCESS_TOKEN: secrets.CONTENTFUL_ACCESS_TOKEN
      - run: yarn
      - run: yarn build
      - run: echo "edwarddeveretruthersociety.org" > ./public/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public